app/views/home.py
from flask import flash
from flask import Blueprint, render_template, request
from app.models import db, Person, Log

home_blueprint = Blueprint("home", __name__)


@home_blueprint.route("/")
def home():
    return render_template("home.html")


@home_blueprint.route("/log")
def log():
    all_logs = Log.query.all()
    return render_template("log.html", logs=all_logs)

app/views/lister.py
from flask import flash, redirect, url_for
from flask import Blueprint, render_template, request
from app.models import db, Person, Mail, person_identifier

lister_blueprint = Blueprint("lister", __name__)


@lister_blueprint.route("/")
def lister():
    all_persons = Person.query.all()
    return render_template("lister.html", persons=all_persons)


@lister_blueprint.route("/<id>", methods=["POST"])
def update_mailliste_for_person(id):
    error = None
    person_to_update = Person.query.filter_by(person_id=id).first()
    medlem_checked = "medlem" in request.form.getlist("maillist")
    fredagsbar_checked = "fredagsbar" in request.form.getlist("maillist")

    mail_to_update = Mail.query.filter_by(mail_id=1).first()
    if medlem_checked:
        if person_to_update not in mail_to_update.persons:
            mail_to_update.persons.append(person_to_update)

    else:
        if person_to_update in mail_to_update.persons:
            mail_to_update.persons.remove(person_to_update)

    db.session.add(mail_to_update)
    db.session.commit()
    mail_to_update = Mail.query.filter_by(mail_id=3).first()
    if fredagsbar_checked:
        if person_to_update not in mail_to_update.persons:
            mail_to_update.persons.append(person_to_update)
    else:
        if person_to_update in mail_to_update.persons:
            mail_to_update.persons.remove(person_to_update)

    db.session.add(mail_to_update)
    db.session.commit()
    flash(person_to_update.person_fistName + " er nu opdateret!")
    return redirect(url_for("lister.lister"))

app/views/mail.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import os
import requests
import json
from flask import Blueprint, render_template, request
from flask import flash, redirect, url_for, send_from_directory
from flask import jsonify, current_app
from app.models import db, Person, SmsTextMessage, MailTextMessage, Mail, Log
import threading
from flask import current_app as app
from werkzeug.utils import secure_filename
import time
from datetime import datetime as datetime1
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.utils import formataddr
from email import encoders
from email.mime.base import MIMEBase
import smtplib
import datetime


mail_blueprint = Blueprint("mail", __name__)
maillogtext_list = []
path_and_filename = ""
filename = ""
subject = ""


@mail_blueprint.route("/")
def home():
    return render_template("mail.html")


@mail_blueprint.route("/fredagsbar", methods=["GET", "POST"])
def fredagsbar():
    mailtype_fredagsbar = Mail.query.filter_by(mail_id=3).first()
    mailtext = (
        MailTextMessage.query.filter_by(
            mailtextmessage_id=mailtype_fredagsbar.mailTextmessage_id
        )
        .first()
        .text
    )
    smstype_fredagsbar = Mail.query.filter_by(mail_id=1).first()
    smstext = (
        SmsTextMessage.query.filter_by(
            smstextmessage_id=smstype_fredagsbar.smsTextmessage_id
        )
        .first()
        .text
    )
    mailsenddate = time.strftime("%d-%m-%Y %H:%M")
    today = datetime1.today()
    friday = today + datetime.timedelta((4 - today.weekday()) % 7)
    friday_six_oclock = friday.replace(hour=6, minute=0)
    smssenddate = friday_six_oclock.strftime("%d-%m-%Y %H:%M")
    if request.method == "POST":
        all_fredagsbar = Person.query.filter(
            Person.mailslists.any(mail_name="fredagsbar")
        ).all()
        thread = threading.Thread(
            target=fredagsbar_worker,
            args=(
                mailtext,
                smstext,
                all_fredagsbar,
                db,
                current_app._get_current_object(),
                friday_six_oclock,
            ),
        )
        thread.start()
        return render_template("fredagsbarSending.html")

    return render_template(
        "fredagsbar.html",
        mailtext=mailtext,
        smstext=smstext,
        smssenddate=smssenddate,
        mailsenddate=mailsenddate,
    )


@mail_blueprint.route("/medlemmerpdf", methods=["GET", "POST"])
def medlemmerPDF():
    if request.method == "POST":
        global path_and_filename
        global filename
        # check if the post request has the file part
        if "file" not in request.files:
            flash("No file part")
            return redirect(request.url)
        file = request.files["file"]
        # if user does not select file, browser also
        # submit an empty part without filename
        if file.filename == "":
            flash("Der er ikke valgt en fil!")
            return redirect(request.url)
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            path_and_filename = os.path.join(
                app.root_path, app.config["UPLOAD_FOLDER"], filename
            )
            file.save(path_and_filename)

            mailtype_medlem = Mail.query.filter_by(mail_id=1).first()
            mailtext = (
                MailTextMessage.query.filter_by(
                    mailtextmessage_id=mailtype_medlem.mailTextmessage_id
                )
                .first()
                .text
            )

            return render_template(
                "medlemmerPdf.html", filename=filename, mailtext=mailtext
            )
    return render_template("medlemmerPdf.html")


@mail_blueprint.route("/medlemmer", methods=["GET", "POST"])
def medlemmer():
    if request.method == "GET":
        
        mailtype_medlem = Mail.query.filter_by(mail_id=1).first()
        mailtext = (
            MailTextMessage.query.filter_by(
                mailtextmessage_id=mailtype_medlem.mailTextmessage_id
            )
            .first()
            .text
        )

        return render_template(
            "medlemmer.html", mailtext=mailtext
        )
    return render_template("medlemmer.html")


@mail_blueprint.route("/fredagsbartekster")
def fredagsbartekster():
    all_mailtexts = MailTextMessage.query.all()
    all_smstexts = SmsTextMessage.query.all()

    return render_template(
        "fredagsbartekster.html",
        sms_text_messages=all_smstexts,
        mail_text_messages=all_mailtexts,
    )


@mail_blueprint.route("/medlemstekster")
def medlemstekster():
    all_mailtexts = MailTextMessage.query.all()
    all_smstexts = SmsTextMessage.query.all()

    return render_template(
        "medlemstekster.html",
        sms_text_messages=all_smstexts,
        mail_text_messages=all_mailtexts,
    )


@mail_blueprint.route("/oprettekster")
def opret_tekster():
    return render_template("opret-tekster.html")


@mail_blueprint.route("/oprettekster/smstext", methods=["POST"])
def create_smstext():
    name = request.form["tekstName"]
    text = request.form["smstext"]

    newtext = SmsTextMessage(name=name, text=text)
    db.session.add(newtext)
    db.session.commit()
    flash("SMS tekst er nu oprettet!")
    return redirect(url_for("mail.opret_tekster"))


@mail_blueprint.route("/oprettekster/mailtext", methods=["POST"])
def create_mailtext():
    name = request.form["tekstName"]
    text = request.form["mailtext"]

    newtext = MailTextMessage(name=name, text=text)
    db.session.add(newtext)
    db.session.commit()
    flash("Mail tekst er nu oprettet!")
    return redirect(url_for("mail.opret_tekster"))


@mail_blueprint.route("/getfredagsbarmailtext/<id>")
def getfredagsbarmailtext(id):
    # save selecte text in DB
    mailtype = Mail.query.filter_by(mail_id=3).first()
    mailtype.mailTextmessage_id = id
    db.session.commit()
    return MailTextMessage.query.filter_by(mailtextmessage_id=id).first().text


@mail_blueprint.route("/getfredagsbarsmstext/<id>")
def getfredagsbarsmstext(id):
    # save selecte text in DB
    mailtype = Mail.query.filter_by(mail_id=3).first()
    mailtype.smsTextmessage_id = id
    db.session.commit()
    return SmsTextMessage.query.filter_by(smstextmessage_id=id).first().text


@mail_blueprint.route("/getmedlemsmailtext/<id>")
def getmedlemsmailtext(id):
    # save selecte text in DB
    mailtype = Mail.query.filter_by(mail_id=1).first()
    mailtype.mailTextmessage_id = id
    db.session.commit()
    return MailTextMessage.query.filter_by(mailtextmessage_id=id).first().text


@mail_blueprint.route("/getmedlemssmstext/<id>")
def getmedlemssmstext(id):
    # save selecte text in DB
    mailtype = Mail.query.filter_by(mail_id=1).first()
    mailtype.smsTextmessage_id = id
    db.session.commit()
    return SmsTextMessage.query.filter_by(smstextmessage_id=id).first().text


@mail_blueprint.route("/edittext/mailtext", methods=["POST"])
def edit_mailtext():
    text = request.form["mailtext"]
    textName = request.form["medlemsmailtekster"]

    mailtype = Mail.query.filter_by(mail_id=3).first()
    text_id = mailtype.mailTextmessage_id
    newtext = MailTextMessage.query.filter_by(name=textName).first()

    newtext.text = text
    db.session.commit()
    flash("Mail tekst er nu opdateret!")
    return redirect(url_for("home.home"))


@mail_blueprint.route("/edittext/smstext", methods=["POST"])
def edit_smstext():
    text = request.form["smstext"]
    textName = request.form["medlemssmstekster"]

    mailtype = Mail.query.filter_by(mail_id=3).first()
    text_id = mailtype.smsTextmessage_id
    newtext = SmsTextMessage.query.filter_by(name=textName).first()

    newtext.text = text
    db.session.commit()
    flash("SMS tekst er nu opdateret!")
    return redirect(url_for("home.home"))


def allowed_file(filename):
    ALLOWED_EXTENSIONS = app.config["ALLOWED_EXTENSIONS"]
    return "." in filename and filename.rsplit(".", 1)[1].lower() in ALLOWED_EXTENSIONS


@mail_blueprint.route("/uploads/<filename>")
def uploaded_file(filename):
    return send_from_directory(app.config["UPLOAD_FOLDER"], filename)


@mail_blueprint.route("/sendmail/medlemmer", methods=["POST"])
def sendmail_medlemmer():
    global subject
    subject = request.form["subject"]
    if subject != "":
        flash("Der sendes nu mail til medlemmerne!")
        return redirect(url_for("mail.medlemmer_sending"))
    flash("Udfyld venligst emnefelt!")
    return redirect(url_for("mail.medlemmer"))


@mail_blueprint.route("/medlemmersending")
def medlemmer_sending():
    mailtype_medlem = Mail.query.filter_by(mail_id=1).first()
    mailtext = (
        MailTextMessage.query.filter_by(
            mailtextmessage_id=mailtype_medlem.mailTextmessage_id
        )
        .first()
        .text
    )
    all_members = Person.query.filter(Person.mailslists.any(mail_name="medlem")).all()
    thread = threading.Thread(
        target=members_worker,
        args=(mailtext, all_members, db, current_app._get_current_object()),
    )
    thread.start()
    return render_template("medlemmerSending.html")


def members_worker(mailtext, all_members, db, app):
    print("Starter mail udsendelse\n")
    del maillogtext_list[:]
    today = datetime1.now()
    COMMASPACE = ", "
    me = app.config["ME"]
    time_str = time.strftime("%Y-%m-%d %H:%M:%S")

    with app.app_context():
        for member in all_members:
            if member.person_email is not None and member.person_email != "":
                print(member.person_email)
                print(member.person_fistName)
                msg = MIMEMultipart("html")
                msg["Subject"] = subject
                msg["From"] = formataddr(
                    ("Allerup Thorup -kultur og beboerforening", me)
                )
                msg["To"] = member.person_email

app/views/person.py
from flask import flash, redirect, url_for
from flask import Blueprint, render_template, request
from app.models import db, Person

person_blueprint = Blueprint("person", __name__)


@person_blueprint.route("/", methods=["GET"])
def person():
    all_persons = Person.query.all()
    return render_template("person.html", persons=all_persons)


@person_blueprint.route("/", methods=["POST"])
def createPerson():
    error = None

    first_name = request.form["firstName"]
    last_name = request.form["lastName"]
    email = request.form["email"]
    phone = request.form["phone"]
    if email == u"":
        email = None
    if phone == u"":
        phone = None
    if first_name is None:
        first_name = " "
    if phone and len(phone) == 8:
        phone = "45" + phone
    if phone and len(phone) < 8:
        flash("Fejl i telefonnummer!")
        return redirect(url_for("person.person"))

    newPerson = Person(
        person_fistName=first_name,
        person_lastName=last_name,
        person_email=email,
        person_phone=phone,
    )
    db.session.add(newPerson)
    db.session.commit()
    flash("Personen " + first_name + " er nu oprettet!")
    all_persons = Person.query.all()
    return render_template("person.html", persons=all_persons)


@person_blueprint.route("/<id>", methods=["POST"])
def deletePerson(id):
    error = None
    person_to_delete = Person.query.filter_by(person_id=id).first()
    if person_to_delete is not None:
        db.session.delete(person_to_delete)
        db.session.commit()
        flash("Personen " + person_to_delete.person_fistName + " er nu slettet!")
    all_persons = Person.query.all()
    return render_template("person.html", persons=all_persons)

app/templates/base.html
<!-- templates/base.html -->

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>ATKB mailudsend</title>
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" /> -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('home.home') }}">Forside </a>
                </li>
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('person.person') }}">Personer</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('lister.lister') }}">Lister</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Tekster
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ url_for('mail.medlemstekster') }}">Vælg medlemstekster</a>
                        <a class="dropdown-item" href="{{ url_for('mail.fredagsbartekster') }}">Vælg
                            fredagsbartekster</a>
                        <a class="dropdown-item" href="{{ url_for('mail.opret_tekster') }}">Opret tekster</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Send mails
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ url_for('mail.fredagsbar') }}">Fredagsbar</a>
                        <a class="dropdown-item" href="{{ url_for('mail.medlemmer') }}">Medlemmer</a>
                        <a class="dropdown-item" href="{{ url_for('mail.medlemmerPDF') }}">Medlemmer med PDF</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('home.log') }}">Log</a>
                </li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a href="{{ url_for('logout') }}" class="nav-link">
                        Log out
                    </a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a href="{{ url_for('google.login') }}" class="nav-link">
                        Log in med Google
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container-fluid">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>{{ message }}</strong>
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}

        {% block content %}
        {% endblock %}
    </div>
    <script src="{{url_for('static', filename='jquery-3.4.1.min.js')}}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    <script src="{{url_for('static', filename='atkb.js')}}"></script>
    {% block js %}
    {% endblock %}
</body>

</html>

app/templates/fredagsbar.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-12">
        <h1 class="text-center text-info font-weight-bold mt-3">
            Fredagsbar mailudsendelse
        </h1>
    </div>
</div>
<div class="row mt-5">
    <div class="col-md-10 offset-md-1">
        <div class="row">
            <div class="col-md-12 ">
                <div class="form-group">
                    <label for="firstName">Mailtekst:</label><span class="float-right">Send dato:
                        {{mailsenddate}}</span>
                    <textarea class="form-control" disabled rows="13" cols="15" maxlength="1000" id="mailtext"
                        name="mailtext">{{mailtext}}</textarea>
                </div>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-12 ">
                <div class="form-group">
                    <label for="firstName">Smstekst:</label><span class="float-right">Send dato: {{smssenddate}}</span>
                    <textarea class="form-control" disabled maxlength="318" rows="7" cols="15" id="smstext"
                        name="smstext">{{smstext}}</textarea>
                </div>
            </div>
        </div>
    </div>
</div>
<form method="POST">
    <div class="row">
        <div class="col-md-10 offset-md-1">
            <div class="form-group float-right">
                <button type="submit" class="btn btn-primary">Send mail og SMS til alle fredagsbar modtagere
                </button>
            </div>
        </div>
    </div>
</form>


{% endblock %}

app/templates/fredagsbarSending.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-12">
        <h1 class="text-center text-info font-weight-bold mt-3">
            Fredagsbar mailudsendelse er igang
        </h1>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table" id="mail_send">
            <thead>
                <tr>
                    <th>Tid</th>
                    <th>Sendt til</th>
                    <th>Mail adr.</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

{% endblock %}
{% block js %}
<script>
    setInterval(                               //Periodically 
        function () {
            $.getJSON(                            //Get some values from the server
                'https://' + document.domain + ':' + location.port + '/mail/sendmaillogtext',      // At this URL
                {},                                // With no extra parameters
                function (data)                     // And when you get a response
                {
                    var tbl_body = "";
                    var odd_even = false;
                    $.each(data, function () {
                        var tbl_row = "";
                        tbl_row += "<td>" + this.time + "</td>";
                        tbl_row += "<td>" + this.sendto + "</td>";
                        tbl_row += "<td>" + this.email_adr + "</td>";
                        tbl_body += "<tr class=\"" + (odd_even ? "odd" : "even") + "\">" + tbl_row + "</tr>";
                        odd_even = !odd_even;
                    })
                    $("#mail_send tbody").html(tbl_body);
                });
        },
        1000);                                    
</script>
{% endblock %}

app/templates/fredagsbartekster.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-12">
        <h1 class="text-center text-info font-weight-bold mt-3">
            Vælg fredagsbar tekster
        </h1>
    </div>
</div>

<form method="post" action="./edittext/mailtext">
    <div class="row mt-5">
        <div class="col-md-10 border offset-md-1">
            <div class="row">
                <div class="col-md-12 ">
                    <div class="form-group">
                        <label for="tekster">Tekster:</label>
                        <select class="form-control" name="medlemsmailtekster" id="medlemsmailtekster"
                            placeholder="nodet">
                            <option value="" disabled selected>Vælg en tekst.</option>
                            {% for text in mail_text_messages %}
                            <option id="{{text.mailtextmessage_id}}">{{ text.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 ">
                    <div class="form-group">
                        <label for="firstName">Mailtekst:</label>
                        <p>Fredagsbar på fredag i Allerup Forsamlingshus</p>
                        <textarea class="form-control" rows="15" cols="15" maxlength="1000" id="mailtext"
                            name="mailtext"></textarea>
                    </div>

                </div>
            </div>
            <div class="row">
                <div class="col-md-12 ">
                    <pre class="float-left">Næste fredag dato: ##dato##  &nbsp; Fornavn: ##navn##</pre>
                    <div class="form-group float-right">
                        <button type="submit" class="btn btn-primary">Opdater</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<form method="post" action="./edittext/smstext">
    <div class="row mt-5">
        <div class="col-md-10 border offset-md-1">
            <div class="row">
                <div class="col-md-12 ">
                    <div class="form-group">
                        <label for="tekster">Tekster:</label>
                        <select class="form-control" name="medlemssmstekster" id="medlemssmstekster"
                            placeholder="nodet">
                            <option value="" disabled selected>Vælg en tekst.</option>
                            {% for text in sms_text_messages %}
                            <option id="{{text.smstextmessage_id}}">{{ text.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 ">
                    <div class="form-group">
                        <label for="firstName">SMStekst:</label>
                        <textarea class="form-control" maxlength="318" rows="8" cols="15" id="smstext"
                            name="smstext"></textarea>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 ">
                    <pre class="float-left">Næste fredag dato: ##dato##  &nbsp; Fornavn: ##navn##</pre>
                    <div class="form-group float-right">
                        <button type="submit" class="btn btn-primary">Opdater</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

app/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <h1 class="text-center text-info font-weight-bold mt-3">
      Allerup, Thorup kultur og beboerforeningmailudsendelse
    </h1>
    <h2 class="text-center text-info">
      Sender individuelle mails ud til fredagsbarmail modtagere og medlemmer
    </h2>
    <p class="text-center">
      {% if current_user.is_authenticated %}
      Du er logget ind som {{ current_user.given_name }}!
    </p>
    <p class="text-center">
      <a href="{{ url_for('logout') }}">Log out</a>
      {% else %}
      You are not logged in.
      <a href="{{ url_for('google.login') }}">Log in med Google</a>
      {% endif %}
    </p>
  </div>
</div>
{% endblock %}

app/templates/lister.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-12">
        <h1 class="text-center text-info font-weight-bold mt-3">
            Mail lister
        </h1>
    </div>
</div>

{% if persons %}
<div class="row">
    <div class="col-md-10 offset-md-1 pr-0 pl-0">
        <table class="table border" style="height: 250px; overflow-y: scroll;">
            <thead>
                <tr>
                    <th scope="col"></th>
                    <th scope="col">Fornavn</th>
                    <th scope="col">Efternavn</th>
                    <th scope="col">Medlem</th>
                    <th scope="col">Fredagsbar</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for person in persons %}
                <tr>
                    <th scope="row">{{person.person_id}}</th>
                    <td>{{person.person_fistName}}</td>
                    <td>{{person.person_lastName}}</td>
                    <form action="/lister/{{person.person_id}}" method="POST">
                        <td><input type="checkbox" name="maillist" value="medlem"
                                {% for mailtype in person.mailslists %} {% if mailtype.mail_name == 'medlem' %} checked
                                {% endif %} {% endfor %} /></td>
                        <td><input type="checkbox" name="maillist" value="fredagsbar"
                                {% for mailtype in person.mailslists %} {% if mailtype.mail_name == 'fredagsbar' %}
                                checked {% endif %} {% endfor %} /></td>
                        <td>
                            <button class="btn btn-sm" type="submit">Opdatere </button>
                        </td>
                    </form>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endif %}
{% endblock %}

app/templates/medlemmerPdf.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-12">
        <h1 class="text-center text-info font-weight-bold mt-3">
            Medlemmer mailudsendelse med PDF
        </h1>
    </div>
</div>

{% if not filename %}
<form method="post" class="form-control-file" enctype="multipart/form-data">
    <div class="row">
        <div class="col-md-10 offset-md-1 mt-3">
            <input type="file" name="file" />
            <button type="submit" class="btn btn-primary">Upload</button>
        </div>
    </div>
</form>
{% endif%}
{% if filename %}
<div class="row">
    <div class="col-md-10 offset-md-1 mt-3">
        <a href="{{ url_for('mail.uploaded_file', filename=filename) }}" target="_blank"> Se vedhæftet file:
            {{filename}}
        </a>
    </div>
</div>
<div class="row">
    <div class="col-md-10 offset-md-1 mt-3">
        <div class="form-group">
            <label for="mailtext">Mailtekst:</label>
            <textarea disabled class="form-control" rows="15" cols="15" maxlength="1000" id="mailtext"
                name="mailtext">{{mailtext}}</textarea>
        </div>
    </div>
</div>
<form method="POST" action="./sendmail/medlemmer">
    <div class="row">
        <div class="col-md-10 offset-md-1">
            <div class="form-group">
                <label for="tekstName">Emne:</label>
                <input type="text" class="form-control" id="subject" name="subject">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-10 offset-md-1">
            <div class="form-group float-right">
                <button type="submit" class="btn btn-primary">Send mail til alle medlemmer</button>
            </div>
        </div>
    </div>
</form>
{% endif%}
{% endblock %}